my_mdb/movie/urls.py
from django.urls import path
from . import views

app_name='movie'

urlpatterns = [
    path('', views.MovieList.as_view(), name="movies_list"),
    path('category/<str:category>/', views.MovieCategory.as_view(), name="movie_category"),
    path('language/<str:lang>/', views.MovieLanguage.as_view(), name="movie_language"),
    path('search/', views.MovieSearch.as_view(), name="movie_search"),
    path('year/<int:year>/', views.MovieYear.as_view(), name="movie_year"),
    path('<str:slug>/', views.MovieDetail.as_view(), name="movie_detail")
]

my_mdb/my_mdb/urls.py
from django.contrib import admin
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from django.urls.conf import include
from movie import views

urlpatterns = [
    path('', views.HomeView.as_view(), name="home"),
    path('admin/', admin.site.urls),
    path('movies/', include('movie.urls', namespace="movies")),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

my_mdb/movie/models.py
from django.db import models
from django.utils.text import slugify

CATEGORY_CHOICES = (
    ('action', 'ACTION'),
    ('comedy', 'COMEDY'),
    ('drama', 'DRAMA'),
    ('fantasy', 'FANTASY'),
    ('horror', 'HORROR'),
    ('kids', 'KIDS'),
    ('romance', 'ROMANCE'),
    ('science-fiction', 'SCIENCE-FICTION'),
)

LANGUAGE_CHOICES = (
    ('english', 'ENGLISH'),
    ('french', 'FRENCH'),
)

STATUS_CHOICES = (
    ('RA', 'RECENTLY ADDED'),
    ('MW', 'MOST WATCHED'),
    ('TR', 'TOP RATED'),
)

class Movie(models.Model):

    title = models.CharField(max_length=100)
    description = models.TextField(max_length=1000)
    image = models.ImageField(upload_to='movies')
    banner = models.ImageField(upload_to='movies_banner')
    category = models.CharField(choices=CATEGORY_CHOICES, max_length=15)
    language = models.CharField(choices=LANGUAGE_CHOICES, max_length=8)
    status = models.CharField(choices=STATUS_CHOICES, max_length=2)
    cast = models.CharField(max_length=100)
    year_of_production = models.DateField()
    views_count = models.IntegerField(default=0)
    slug = models.SlugField(blank=True, null=True)
    trailer = models.URLField(blank=True)
    created_at = models.DateTimeField(auto_now_add=True)

    def save(self, force_insert: bool = True, force_update: bool = True, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.title)
        super(Movie, self).save(*args, **kwargs)

    def __str__(self) -> str:
        return self.title

LINK_CHOICES = (
    ('Download', 'DOWNLOAD LINK'),
    ('Watch', 'WATCH LINK'),
)

class Movielink(models.Model):
    movie = models.ForeignKey(Movie, related_name='movie_watch_link', on_delete=models.CASCADE)
    type = models.CharField(choices=LINK_CHOICES, max_length=8)
    link = models.URLField()

    def __str__(self):
        string = str(self.movie) + ' | ' + str(self.type)
        return string

my_mdb/movie/views.py
from django.db.models.query import QuerySet
from django.http.response import HttpResponseBadRequest
from django.shortcuts import get_object_or_404, render
from django.views.generic import ListView, DetailView, YearArchiveView
from django.views.generic.dates import YearArchiveView
from .models import Movie, Movielink

# def index(request):
#     if request.method == 'GET':
#         return render(request, 'movie/index.html')
#     else:
#         return HttpResponseBadRequest('Bad request')

class HomeView(ListView):
    model = Movie
    template_name = 'movie/index.html'
    def get_context_data(self, **kwargs):
        context = super(HomeView, self).get_context_data(**kwargs)
        context['top_rated'] = Movie.objects.filter(status='TR')
        context['most_watched'] = Movie.objects.filter(status='MW')
        context['recently_added'] = Movie.objects.filter(status='RA')
        print(context)
        return context

class MovieList(ListView):
    model = Movie
    template_name='movie/movie_list.html'
    paginate_by = 2

class MovieDetail(DetailView):
    model = Movie
    template_name='movie/movie_detail.html'
    
    def get_object(self):
        object = super(MovieDetail, self).get_object()
        # object.views_count += 1
        # object.save()
        return object

    def get_context_data(self, **kwargs):
        context = super(MovieDetail, self).get_context_data(**kwargs)
        context['links'] = Movielink.objects.filter(movie=self.get_object())
        context['related_movies'] = Movie.objects.filter(category=self.get_object().category).exclude(id=self.get_object().id).order_by('created_at')[:6]
        print(context['related_movies'])
        return context

class MovieCategory(ListView):
    model = Movie
    paginate_by = 2
    def get_queryset(self):
        self.category = self.kwargs['category']
        movies = Movie.objects.filter(category=self.category)
        print(self.category)
        return movies
        # return Movie.objects.filter(category=self.category)

    def get_context_data(self, **kwargs):
        context = super(MovieCategory, self).get_context_data(**kwargs)
        context['movie_category'] = self.category
        return context
        
class MovieLanguage(ListView):
    model = Movie
    paginate_by = 2

    def get_queryset(self):
        self.language = self.kwargs['lang']
        movies = Movie.objects.filter(language=self.language)
        print(self.language)
        return movies
        # return Movie.objects.filter(category=self.category)

    def get_context_data(self, **kwargs):
        context = super(MovieLanguage, self).get_context_data(**kwargs)
        context['movie_language'] = self.language
        return context

class MovieSearch(ListView):
    model = Movie
    paginate_by = 2

    def get_queryset(self):
        query = self.request.GET.get('query')
        if query:
            object_list = Movie.objects.filter(title__icontains=query)
        else:
            object_list = Movie.objects.all()
        return object_list

    # def get_context_data(self, **kwargs):
    #     context = super(MovieLanguage, self).get_context_data(**kwargs)
    #     context['movie_language'] = self.language
    #     return context

class MovieYear(YearArchiveView):
    movies = Movie.objects.all()
    date_field = 'year_of_production'
    make_object_list = True
    allow_future = True
    
    template_name = 'movie/movie_list.html'

    def get_allow_empty(self) -> bool:
        return True

    def get_queryset(self):
        return self.movies

my_mdb/movie/templates/movie/index.html
{% extends 'base.html' %}

{% block content %}

<section class="panel">
    <h2>Recently added</h2>
    {% if recently_added %}
    
    
    <!-- Slider main container -->
  <div class="swiper">
    <!-- Additional required wrapper -->
    <div class="swiper-wrapper">
      <!-- Slides -->
      {% for movie in recently_added %}
      
        <div class="swiper-slide">
            <a href="{% url 'movies:movie_detail' movie.slug %}">
                <img class="img-fluid" src="{{movie.image.url}}" alt="{{movie.title}}">
                <h2 class="movietitle">{{movie.title}}</h2>
            </a>
        </div>
      {% empty %}
        <div class="alert alert-warning ">Aucun film à afficher</div>
      {% endfor %}
    </div>

    <!-- If we need navigation buttons -->
    <div class="swiper-button-prev"></div>
    <div class="swiper-button-next"></div>
  </div>
  {% else %}
    
        <div class="alert alert-warning ">Aucun film à afficher</div>

    {% endif %}
</section>

<section class="panel">
    <h2>Top rated</h2>
    {% if top_rated %}
    
   
    <div class="swiper">
    <!-- Additional required wrapper -->
    <div class="swiper-wrapper">
      <!-- Slides -->
      {% for movie in top_rated %}
        <div class="swiper-slide">
            <a class="d-flex flex-column h-100" href="{% url 'movies:movie_detail' movie.slug %}">
                <img class="img-fluid h-100" src="{{movie.image.url}}" alt="{{movie.title}}">
                <h3 class="movietitle mt-auto pb-4">{{movie.title}}</h3>
            </a>
        </div>
      {% endfor %}
    </div>
    <!-- If we need pagination -->
    {% comment %} <div class="swiper-pagination">
    </div>
   {% endcomment %}
    <!-- If we need navigation buttons -->
    <div class="swiper-button-prev"></div>
    <div class="swiper-button-next"></div>
  </div>
    {% else %}
    
        <div class="alert alert-warning ">Aucun film à afficher</div>

    {% endif %}
</section>
<section class="panel">
    <h2>Most watched</h2>
    {% if most_watched %}
    
    <div class="swiper">
    <!-- Additional required wrapper -->
    <div class="swiper-wrapper">
      <!-- Slides -->
      {% for movie in most_watched %}

        <div class="swiper-slide">
            <a class="d-flex flex-column h-100" href="{% url 'movies:movie_detail' movie.slug %}">
                <img class="img-fluid h-100" src="{{movie.image.url}}" alt="{{movie.title}}">
                <h3 class="movietitle mt-auto pb-4">{{movie.title}}</h3>
            </a>
        </div>

        </div>
      {% endfor %}
    </div>
    <!-- If we need pagination -->
    {% comment %} <div class="swiper-pagination">
    </div> {% endcomment %}
  
   <!-- If we need navigation buttons -->
    <div class="swiper-button-prev"></div>
    <div class="swiper-button-next"></div>
  
  </div>
  {% else %}
    
        <div class="alert alert-warning ">Aucun film à afficher</div>

    {% endif %}
</section>

{% endblock %}

{% block js %}
    <script>
        const swiper = new Swiper('.swiper', {
            // Optional parameters
            direction: 'horizontal',
            loop: true,

            {% comment %} slidesPerView: 3, {% endcomment %}

            // If we need pagination
            pagination: {
                el: '.swiper-pagination',
            },

            // Navigation arrows
            navigation: {
                nextEl: '.swiper-button-next',
                prevEl: '.swiper-button-prev',
            },

            // And if we need scrollbar
            scrollbar: {
                el: '.swiper-scrollbar',
            },
        });
    </script>
{% endblock %}

my_mdb/movie/templates/movie/movie_detail.html
{% extends "base.html" %}

{% block content %}
<div class="layout">
    <section class="trailer">
        <h3>Trailer</h3>
        <div class="trailer_frame">
            <iframe src="{{object.trailer}}" width="560" height="315" frameborder="0" allowfullscreen></iframe>
        </div>
    </section>
    <section class=" movie">
        <div class="row">

                <div class="relatedmovie card bg-dark">
                    <img class="img-fluid movie_card_img" src="{{object.image.url}}" alt="{{object.title}}">
                </div>
                <div class="col-3">
                    <div class="movie_text">
                        <h2>{{object.title}}</h2>
                        <p class="movie_detail_text">
                            {{object.category}} <br>
                            <a href=''>{{object.cast}}</a>
                        </p>
                        <p>{{object.views_count}} Vues</p>
                    </div>
                </div>
                <div class="col">
                    <div class="mt-4">
                        {% comment %} {{movie.description}} {% endcomment %}
                    </div>
                </div>

        </div>
    </section>
    <section class="links_block">
        <div class="row no-gutters">
            <h3 class="mb-3">Liens</h3>
        </div>

            <div class="dlinks links mb-3">
                <div><a class="btn btn-danger">Télécharger</a></div>
                {% for link in links %}
                    {% if link.type == "D" %}
                        <div><a class="btn btn-danger" href="{{link.link}}">Lien{{forloop.counter}} </a></div>
                    {% endif %}
                {% endfor %}
            </div>
            <div class="wlinks links mb-3">
                <div><a class="btn btn-danger">Regarder</a></div>
                {% for link in links %}
                    {% if link.type == "W" %}
                        <div><a class="btn btn-danger" href="{{link.link}}">Lien{{forloop.counter}}</a></div>
                    {% endif %}
                {% endfor %}
            </div>
    </section>
    <section class="related">
        <h3>Films similaires</h3>
        <div class="row">
        {% for movie in related_movies %}
            <div class="relatedmovie card bg-dark">
                <a href="{% url 'movies:movie_detail' movie.slug %}"><img class="movie_card_img img-fluid" src="{{movie.image.url}}" alt="{{movie.title}}"></a>
                <a href="{% url 'movies:movie_detail' movie.slug %}"><span class="relatedname">{{movie.title}}</span></a>
            </div>
        {% endfor %}
        </div>
    </section>
</div>
{% endblock %}

my_mdb/movie/templates/movie/movie_list.html
{% extends "base.html" %}

{% block content %}
{% load static %}
<section class='layout text-center'>
    {% if movie_category %}
        <h3 class="mb-5">{{movie_category|title}}</h3>
    {% endif %}
    {% if movie_language %}
        <h3 class="mb-5">{{movie_language | title}}</h3>
    {% endif %}
    {% if year %}
        <h3 class="mb-5">Films de l'année {{year|date:"Y"}}</h3>
    {% endif %}
    <div class="movies row mb-5">
        {%  for movie in object_list%}
            <div class="mov col">
                <a href="{% url 'movies:movie_detail' movie.slug %}">
                    <img class="img-fluid" src="{{movie.image.url}}" alt="{{movie.title}}">
                    <h2 class="movietitle">{{movie.title}}</h2>
                </a>
            </div>
        {% empty %}
            <h3 class="alert alert-warning my-5 mx-auto">Aucun film dans cette catégorie</h3>
        {% endfor %}
    </div>
    {% comment %} {% if page_obj.has_other_pages %} {% endcomment %}
    {% if is_paginated %}
        
        <nav aria-label="Page navigation">
            <ul class="pagination justify-content-center">
                {% if page_obj.has_previous %}
                    <li class="page-item"><a class="page-link" href="?page=1">&laquo; first</a></li>
                    <li class="page-item"><a class="page-link" href="?page={{ page_obj.previous_page_number }}">Prev</a></li>
                {% else %}
                    <li class="disabled page-item"><a class="page-link" >&laquo; first</a></li>
                    <li class="disabled page-item"><a class="page-link" >Prev</a></li>
                {% endif %}

                {% for page in page_obj.paginator.page_range %}
                    {% if page_obj.number == page %}
                        <li class="page-item"><a class="page-link" >{{page}}</a></li>
                    {% else %}
                        <li class="page-item"><a class="page-link" href="?page={{page}}">{{page}}</a></li>
                    {% endif %}
                {% endfor %}

                {% if page_obj.has_next %}
                    <li class="page-item"><a class="page-link" href="?page={{ page_obj.next_page_number }}">Next</a></li>
                    <li class="page-item"><a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a></li>
                {% else %}
                    <li class="disabled page-item"><a class="page-link" >Next</a></li>
                    <li class="disabled page-item"><a class="page-link" >last &raquo;</a></li>
                {% endif %}
            </ul>
        </nav>
    {% endif %}
</section>
{% endblock content %}

my_mdb/templates/base.html
{% load static %}
<!doctype html>
<html lang="fr">
  <head>
    <title>
    {% block title %}
        Title
    {% endblock title  %}
    </title>
    {% block head %}
        <!-- Required meta tags -->
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

        <!-- Bootstrap CSS -->
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

        <!-- Custom css -->
        <link rel="stylesheet" href="{% static 'css/style.css' %}">

        <!-- Font awesome -->
        <script src="https://kit.fontawesome.com/96486db8a9.js" crossorigin="anonymous"></script>

        <!-- Swipper CDN -->
        <link rel="stylesheet" href="https://unpkg.com/swiper@7/swiper-bundle.min.css"/>
        <script src="https://unpkg.com/swiper@7/swiper-bundle.min.js"></script>

    {% endblock head %}
  </head>
  <body class="min-vh-100 d-flex flex-column">
        {% block header %}
        <nav class="navbar navbar-expand-sm navbar-dark bg-dark">
            <a class="navbar-brand h-100" href="{% url 'home' %}">
                <img class="img-fluid" src="{% static 'img/mymdb.png' %}" alt="Mymdb">
            </a>
            <button class="navbar-toggler d-lg-none" type="button" data-toggle="collapse" data-target="#collapsibleNavId" aria-controls="collapsibleNavId"
                aria-expanded="false" aria-label="Toggle navigation"></button>
            <div class="collapse navbar-collapse" id="collapsibleNavId">
                <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
                    <li class="nav-item ml-5">
                        <a class="nav-link" href="{% url 'home' %}">Accueil <span class="sr-only">(current)</span></a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{%url 'movies:movies_list' %}">Movies</a>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="dropdownId" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Genres</a>
                        <div class="dropdown-menu" aria-labelledby="dropdownId">
                            <a class="dropdown-item" href="{%url 'movies:movie_category' 'action'%}">Action</a>
                            <a class="dropdown-item" href="{%url 'movies:movie_category' 'comedy'%}">Comedie</a>
                            <a class="dropdown-item" href="{%url 'movies:movie_category' 'horror'%}">Horreur</a>
                            <a class="dropdown-item" href="{%url 'movies:movie_category' 'fantasy'%}">Fantaisie</a>
                            <a class="dropdown-item" href="{%url 'movies:movie_category' 'science-fiction'%}">Science-Fiction</a>
                        </div>
                    </li>
                    <!-- <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="dropdownId" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Langage</a>
                        <div class="dropdown-menu" aria-labelledby="dropdownId">
                            <a class="dropdown-item" href="{%url 'movies:movie_language' 'english'%}">Anglais</a>
                            <a class="dropdown-item" href="{%url 'movies:movie_language' 'french'%}">Français</a>
                        </div>
                    </li> -->
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="dropdownId" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Langage</a>
                        <div class="dropdown-menu" aria-labelledby="dropdownId">
                            <a class="dropdown-item" href="{%url 'movies:movie_language' 'english'%}">Anglais</a>
                            <a class="dropdown-item" href="{%url 'movies:movie_language' 'french'%}">Français</a>
                        </div>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="dropdownId" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Année</a>
                        <div class="dropdown-menu" aria-labelledby="dropdownId">
                            <a class="dropdown-item" href="{% url 'movies:movie_year' year=2021 %}">2021</a>
                            <a class="dropdown-item" href="{% url 'movies:movie_year' year=2020 %}">2020</a>
                            <a class="dropdown-item" href="{% url 'movies:movie_year' year=2019 %}">2019</a>
                            <a class="dropdown-item" href="{% url 'movies:movie_year' year=2018 %}">2018</a>
                            <a class="dropdown-item" href="{% url 'movies:movie_year' year=2017 %}">2017</a>
                        </div>
                    </li>
                    <li class="nav-item ml-5">

                        <form class="form-inline my-auto" method="GET" action="{% url 'movies:movie_search' %}">
                            <input class="form-control mr-sm-2 search-input" name="query" value="{{request.GET.query}}" type="text" placeholder="Rechercher...">
                            <button class="btn btn-link my-2 my-sm-0 search-btn text-white" type="submit"><i class="fas fa-search fa-2x"></i></button>
                        </form>
                    </li>
                </ul>
            </div>
        </nav>
        {% endblock header %}
        <div class="slider homeslider">
            <div id="carouselSwiper" class="carousel slide" data-ride="carousel">
                <div class="carousel-inner">
                {% for movie in slider_movies %}
                    <div class="carousel-item {% if forloop.counter0 == 0 %} active{% endif %}">
                        <img class="d-block w-100 carousel-image" src="{{movie.banner.url }}" alt="{{movie.title}}">
                        <div class="carousel-caption">
                            <div class="captioninside">
                                <h3>{{movie.title | title}}</h3>
                                <p>{{movie.description}}</p>
                                <a href="{% url 'movies:movie_detail' movie.slug %}" class="playbutton btn">Lecture</a>
                            </div>
                        </div>
                    </div>
                {% endfor %}
                </div>
                <a class="carousel-control-prev" href="#carouselSwiper" role="button" data-slide="prev">
                    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                    <span class="sr-only">Previous</span>
                </a>
                <a class="carousel-control-next" href="#carouselSwiper" role="button" data-slide="next">
                    <span class="carousel-control-next-icon" aria-hidden="true"></span>
                    <span class="sr-only">Next</span>
                </a>
            </div>
        </div>
        <main class="flex-fill mt-4 content">
            {% block content %}

            {% endblock content %}
        </main>
    
    <footer class="footer pt-4 bg-secondary container-fluid text-white">
        {% block footer %}
            <div class="row no-gutters justify-content-around py-4">
                <div class="col-auto">
                    <div class="footer-menu">
                        <ul>
                            <li><a href="/">Accueil</a></li>
                            <li><a href="/">Contact</a></li>
                            <li><a href="/">Termes et conditions</a></li>
                        </ul>
                    </div>
                </div>
                <div class="col-auto">
                    <div class="tags">
                        <ul>
                            <li>
                                Regarder des bandes annonces gratuites
                            </li>
                            <li>
                                Bandes annonces de films
                            </li>
                            <li>
                                Bandes annonces de films en VOSTE
                            </li>
                            <li>
                                Bandes annonces des nouveaux films
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="copyright text-white text-center mx-auto pb-3">
                    Copyright &copy;-2021
                </div>
            </div>
            
        {% endblock  %}
    </footer>
    
    {% block js %}
    {% endblock  %}
        <!-- Optional JavaScript -->
        <!-- jQuery first, then Popper.js, then Bootstrap JS -->
        <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

  </body>
</html>